name: tiv
version: "v1.0.0"
summary: Terminal Image Viewer
description: |
  NOTE: This snap file doesn't work yet. Checked in for dev purposes.
  tiv is a small C++ program to display images in a (modern) terminal using RGB ANSI codes
  and unicode block graphic characters.

confinement: devmode

apps:
  tiv:
    command: tiv


parts:
  tiv: 
    plugin: autotools
    source-type: tar
    source: https://github.com/stefanhaustein/TerminalImageViewer/archive/v1.0.0.tar.gz
    build-packages:
      - g++
      - make
      - imagemagick



    
    


